# Generated by Django 3.0.8 on 2020-07-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='status',
            field=models.IntegerField(choices=[(1, 'Livre'), (2, 'Em Uso')], default=1, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('1', 'Ativo'), ('2', 'Suspenso'), ('3', 'Com Erro')], default='1', max_length=1, verbose_name='Status'),
        ),
    ]
