# Generated by Django 3.0.8 on 2020-08-13 22:02

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200731_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Title')),
                ('text', djrichtextfield.models.RichTextField()),
            ],
        ),
    ]
