# Generated by Django 3.0.8 on 2020-09-24 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='port',
            name='server',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Server'),
        ),
    ]
