# Generated by Django 3.0.8 on 2020-09-24 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_port_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='port',
            field=models.ForeignKey(limit_choices_to={'status': 1}, on_delete=django.db.models.deletion.CASCADE, to='core.Port'),
        ),
    ]
